name: Check languages

on:
  schedule:
    # Run every Monday at a (more or less) random time
    - cron: '50 8 * * 1'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-languages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # Use the latest LTS version of Node (https://nodejs.org/)
          node-version: 'lts/*'
      - run: npm ci

      - name: Check languages
        run: npm run check-languages
