name: Validate languages

on:
  schedule:
    # Run every Monday at a (more or less) random time
    - cron: '50 8 * * 1'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-languages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # Use the latest LTS version of Node (https://nodejs.org/)
          node-version: 'lts/*'
      - run: npm ci

      - name: Validate languages
        run: npm run validate-languages
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          STACKOVERFLOW_API_KEY: ${{ secrets.STACKOVERFLOW_API_KEY }}
